joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 10
  
mobile_base_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: 'left_wheel_to_base'
  right_wheel: 'right_wheel_to_base'
  publish_rate: 10
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  wheel_separation: 217 # 0.217
  wheel_radius: 70 # 70
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0
  cmd_vel_timeout: 0.25
  base_frame_id: base_footprint
  linear:
    x:
      has_velocity_limits : true
      max_velocity : 0.6 # m/s
      has_acceleration_limits: true
      max_acceleration : 6.0 # m/s^2
  angular:
    z:
      has_velocity_limits : true
      max_velocity : 4.71 # rad/s
      has_acceleration_limits: true
      max_acceleration : 9.42 # rad/s^2
  enable_odom_tf: true
  odom_frame_id: odom
  publish_cmd: true