DWAPlannerROS:
    # Robot configuration parameters 
    acc_lim_x: 2.0
    acc_lim_y: 0.0
    acc_lim_theta: 3.00
    acc_lim_trans: 2.0

    max_vel_trans: 1.0
    min_vel_trans: 0.1

    max_vel_x: 1.0
    min_vel_x: -1.0
    max_vel_y: 0.0
    min_vel_y: 0.0
    max_vel_theta: 7.31
    min_vel_theta: 0.4

    # Goal tolerance parameters
    xy_goal_tolerance: 0.02
    yaw_goal_tolerance: 0.1
    latch_xy_goal_tolerance: true

    # Global plan parameters
    prune_plan: true

#     # ...
#     trans_stopped_vel: 0.1
#     theta_stopped_vel: 0.1

    # Forward simulation parameters
    sim_time: 1.0
    sim_granularity: 0.025
    angular_sim_granularity: 0.1
    vx_samples: 20                  # default 20
    vy_samples: 0
    vth_samples: 40                 # default 40
    controller_frequency: 15.0      # default 10.0

    # Trajectory scoring parameters
    # path_distance_bias: 50.0
    # goal_distance_bias: 40.0        # default
    path_distance_bias: 64.0
    goal_distance_bias: 24.0        # default
    occdist_scale: 0.02
#     twirling_scale: 0.0 

    forward_point_distance: 0.05
#     stop_time_buffer: 0.2           # default
    scaling_speed: 0.25             # default
    max_scaling_factor: 0.2         # default

    # publish_cost_grid_pc: true
    # publish_traj_pc: true

    # Oscillation prevention parameters 
    oscillation_reset_dist: 0.05
    oscillation_reset_angle: 0.2

#     # ...
#     use_dwa: true
#     restore_defaults: false