base_global_planner: global_planner/GlobalPlanner
base_local_planner: dwa_local_planner/DWAPlannerROS
# base_local_planner: teb_local_planner/TebLocalPlannerROS
# base_local_planner: base_local_planner/TrajectoryPlannerROS

# recovery_behaviors: [...]       # default

controller_frequency: 15.0        # default 20.0
planner_patience: 5.0             # default 5.0
controller_patience: 5.0          # default 15.0
conservative_reset_dist: 0.3      # default 3.0
recovery_behavior_enabled: true   # default true
clearing_rotation_allowed: false  # default true
shutdown_costmaps: true           # default false
oscillation_timeout: 3.0          # default 0.0 
oscillation_distance: 0.01        # default 0.5 
planner_frequency: 0.0            # default 0.0
max_planning_retries: 3           # default -1