marker_size: &marker_size_value 0.1

static_markers:
  - id: 21
    size: *marker_size_value
    coordinates:
      x: 0.57
      y: 0.575
  - id: 23
    size: *marker_size_value
    coordinates:
      x: 0.57
      y: 1.5 # 2.425
  - id: 20
    size: *marker_size_value
    coordinates:
      x: 1.43
      y: 0.575
  - id: 22
    size: *marker_size_value
    coordinates:
      x: 1.43
      y: 1.5 # 2.425

cube_markers:
  dolly_cube_markers:
    - id: 20
      x: 0.05
      y: 0
    - id: 25
      x: 0
      y: 0.05
    - id: 26
      x: -0.05
      y: 0
    - id: 27
      x: 0
      y: -0.05
  enemy_cube_markers:
    - id: 21
      x: 0.05
      y: 0
    - id: 29
      x: 0
      y: 0.05
    - id: 30
      x: -0.05
      y: 0
    - id: 31
      x: 0
      y: -0.05
